### ISSUE TITLE
can't make the motor spins correctly

### ISSUE THREAD

**Issue by shaohad** [jaustindavid/wiiceiver#6]
i have this setup:
motor : turnigy 6364 213kv
battery pack 10s li-ion
esc - turnigy 120A HV - opto 
wiiciver (purchased at diyelectricskateboard)
nyko nunchuk remote + usb dongle
5V battery pack instad of ubec

my issue: i benn tring all combinations , i manage to start the wiiciver , seems like it connected to remote.
but motor bips and wont spin when i press forward
i have connected same setup to simple servo tester and its working
any ideas?

**Comment by jaustindavid** [comment]
What do the lights show when you start the wiiceiver?  How do you know it's connecting to the remote?

Were you able to run the setup routine?

**Comment by shaohad** [comment]
how can we speak directly?
skype? so i could show you a video?
my email is shaohad@gmail.com

**Comment by jaustindavid** [comment]
email the video to austin@austindavid.com

**Comment by shaohad** [comment]
email sent
